services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "changeit"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
